name: Deploy Plugin

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build SaaS"]
    types: [completed]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download SaaS Build
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: Copy SaaS Build to Plugin
      run: |
        mkdir -p build
        cp -r build/* build/

    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update SaaS Build
        file_pattern: build/*
